[workspace]
authors = ["Suvash Thapaliya <suvash@gmail.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "hello-world"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
mojo = "==0.25.6"
